### ISSUE TITLE
Figure problem

### ISSUE THREAD

**Issue by cflwzj** [carljohanhoel/BayesianRLForAutonomousDriving#7]
Sorry to have bothered you, how to use code to realize Figure 3 and Figure 4 in the paper? I don't seem to find it in the program you provided. Thank you very much.

**Comment by carljohanhoel** [comment]
Thanks for your question. The provided code was used to train the agents that are described in the paper, but the code that was used to create the plots of the paper is not included. However, these plots can easily be recreated by using the data from the test episodes, which is stored in the .csv files in the folder of your training logs.

Figure 3:
The proportion of collision free test episodes can be extracted from the file test_steps.csv. If the number of steps of an episode is 100, the episode was solved without a collision. Furthermore, the episode returns can be extracted from test_rewards.csv (a better name would have been test_returns.csv).

Figure 4:
The individual Q-values for each action of each test episode are stored in test_individual_qvalues_data.csv. From this data, you can calculate the standard deviation and the coefficient of variation of the Q-values.
